version: "1.0.0"
services: 
  backend:
    container_name: backend # backend
    restart: always
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports: 
      - "8000:8000"
    links: 
      - frontend
    command : bash -c "python manage.py runserver 127.0.0.1:8000"
  frontend:
    container_name: frontend # frontned
    restart: always
    build: 
      context: ./frontend # backend dir
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backkend


